Cleanup of most scripts

diff --git a/npm b/npm
--- a/npm
+++ b/npm
@@ -3,10 +3,10 @@
 source $(dirname "${BASH_SOURCE}")/abash/abash.sh
 
 NPM=${NPM:-/usr/local/bin/npm}
-[ -x "$NPM" ] || die "Cannot execute $NPM"
+[ -x "$NPM" ] || die "cannot execute $NPM"
 
-if arge g; then
-  if [ $# -eq 2 -a "$2" == "soft-update" ]; then
+if arge global; then
+  if [ $# -eq 2 -a "$2" == 'soft-update' ]; then
     for pkg in $(npm -g outdated --parseable --depth=0 | cut -d: -f4); do
       sudo $NPM -g install "$pkg"
     done
diff --git a/surveil b/surveil
--- a/surveil
+++ b/surveil
@@ -1,20 +1,13 @@
 #!/bin/bash
-#
-# Name: surveil
-# Auth: Gavin Lloyd <gavinhungry@gmail.com>
-# Desc: Surveil file(s) and execute command when modified
-#
-# Example: surveil file.less "lessc file.less file.css"
-#
 
 source $(dirname "${BASH_SOURCE}")/abash/abash.sh
-[ $# -ge 1 ] || usage "FILES \"COMMAND\""
+[ $# -ge 1 ] || usage 'FILES "COMMAND"'
 
 FILES=${@:1:$(($#-1))}
 COMMAND=${@: -1}
 
 for FILE in $FILES; do
-  [ -r $FILE ] || die "Cannot read surveillance target: $FILE"
+  [ -r $FILE ] || die "cannot read surveillance target: $FILE"
 done
 
 eval $COMMAND
